# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler to generate a chain with target joint density
#' @param n parameter in Bernoulli distribution
#' @param a parameter in Beta distribution
#' @param b parameter in Beta distribution
#' @return a two-dimensional chain of size 10000
#' @examples
#' \dontrun{
#' sampleC = gibbsC(50, 30, 40)
#' plot(sampleC, cex = 0.5)
#' }
#' @importFrom stats rbinom rbeta
#' @export
gibbsC <- function(n, a, b) {
    .Call('_StatComp21062_gibbsC', PACKAGE = 'StatComp21062', n, a, b)
}

